apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
          - targets:
              - 'host.docker.internal:8000'
      - job_name: 'argocd'
        static_configs:
          - targets:
              - 'host.docker.internal:8082'
            labels:
              app: argocd
