apiVersion: v1
kind: Pod
spec:
  containers:
  - name: custom-agent
    image: selmaguedidi/custom-agent:latest
    command:
      - "/bin/sh"
      - "-c"
      - |
        sleep 99d
  - name: dind
    image: docker:27.1.2
    command: ['cat']
    tty: true
    securityContext:
      runAsUser: 0
    resources:
        limits:
            memory: "2Gi"
            cpu: "1000m"
        requests:
            memory: "500Mi"
            cpu: "500m"
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
